# Generated by Django 3.0.5 on 2020-04-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20200426_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='coder',
        ),
        migrations.AddField(
            model_name='todolist',
            name='usrname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='Coder',
        ),
    ]
